### ISSUE TITLE
Heatmap rounds off values >1000, showing incorrect values in tooltip

### ISSUE THREAD

**Issue by tanya123456789** [ropensci/iheatmapr#57]
The heatmap seems to round off values >1000,leading to incorrect  values being shown in the tooltip.
PFA screenshots
[bug_heatmapr.docx](https://github.com/ropensci/iheatmapr/files/3771533/bug_heatmapr.docx)

**Comment by AliciaSchep** [comment]
The default for the text for tooltips is `text = signif(data, digits = 3)` so yeah it does rounding.  You can pass it the exact data if you don't want the rounding. I'd also consider changing that default so that it only rounds decimal points (I don't think it's great to show 0.8304394739471 in a toolip, but I can see that rounding big numbers might also be undesirable, e.g. 1001.213213 should be 1001.21 instead of 1000)

**Comment by tanya123456789** [comment]
That works. Thanks!
